name: gyp
description: Dart support for GYP.
version: 1.0.0-dev
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/dart_gyp
dependencies:
  args: ">=0.13.5 <0.14.0"
  string_editor: ">=1.0.0-dev <2.0.0"
dev_dependencies:
  test: ">=0.12.15 <0.13.0"